<?xmlversion "1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="1.css"?>
    <!DOCTYPE ALL [
	<!ELEMENT ALL (FACULTY, SPECIALITIES)>
	<!ELEMENT FACULTY (#PCDATA)>
	<!ELEMENT SPECIALITIES (SPECIALITY)>
	<!ELEMENT SPECIALITY (NAME, TIME, EXAM, DEPARTMENT )>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT TIME (#PCDATA)>
	<!ELEMENT EXAM (#PCDATA)>
	<!ELEMENT DEPARTMENT (#PCDATA)>
	<!ENTITY spec "Специальность:">
]>
<ALL>
	<FACULTY>Факультет информационных технологий</FACULTY>
	<SPECIALITIES>
		<SPECIALITY>
			<NAME>&spec; ИСИТ</NAME>
			<TIME>Срок обучения: 4 года</TIME>
			<EXAM>Количество экзаменов: 5</EXAM>
			<DEPARTMENT>Выпускающая кафедра: Кафедра программной инженерии</DEPARTMENT>
		</SPECIALITY>
		<SPECIALITY>
			<NAME>&spec; ПОИТ</NAME>
			<TIME>Срок обучения: 4 года</TIME>
			<EXAM>Количество экзаменов: 5</EXAM>
			<DEPARTMENT>Выпускающая кафедра: Кафедра информационных систем и технологий</DEPARTMENT>
		</SPECIALITY>
		<SPECIALITY>
			<NAME>&spec; ДЭЙВИ</NAME>
			<TIME>Срок обучения: 4 года</TIME>
			<EXAM>Количество экзаменов: 5</EXAM>
			<DEPARTMENT>Выпускающая кафедра: Кафедра информатики и дизайна</DEPARTMENT>
		</SPECIALITY>
		<SPECIALITY>
			<NAME>&spec; ПОИМБС</NAME>
			<TIME>Срок обучения: 4 года</TIME>
			<EXAM>Количество экзаменов: 5</EXAM>
			<DEPARTMENT>Выпускающая кафедра: Кафедра программной инженерии</DEPARTMENT>
		</SPECIALITY>
	</SPECIALITIES>
</ALL>
